from services.ejercicios import Ejercicio


def ejercicios_clase0() -> list[Ejercicio]:
    return [
        # ── BASICOS (SELECT, LIMIT, WHERE) ──
        Ejercicio(
            id="c0_01",
            numero=1,
            titulo="Explora la tabla",
            enunciado="Escribe una consulta que muestre todas las columnas de todos los libros en la tabla lista_larga. Muestra solo los primeros 5 resultados.",
            dificultad="basico",
            sql="SELECT * FROM lista_larga LIMIT 5",
        ),
        Ejercicio(
            id="c0_02",
            numero=2,
            titulo="Titulos solamente",
            enunciado="Muestra unicamente la columna titulo de la tabla lista_larga. Limita a los primeros 10 resultados.",
            dificultad="basico",
            sql="SELECT titulo FROM lista_larga LIMIT 10",
        ),
        Ejercicio(
            id="c0_03",
            numero=3,
            titulo="Titulo y autor",
            enunciado="Muestra las columnas titulo y autor de la tabla lista_larga. Ordena los resultados alfabeticamente por titulo.",
            dificultad="basico",
            sql="SELECT titulo, autor FROM lista_larga ORDER BY titulo",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_04",
            numero=4,
            titulo="Libros del 2023",
            enunciado="Encuentra todos los libros que fueron publicados en el anio 2023. Muestra el titulo y el autor.",
            dificultad="basico",
            sql="SELECT titulo, autor FROM lista_larga WHERE anio = 2023",
        ),
        Ejercicio(
            id="c0_05",
            numero=5,
            titulo="Libros que no son tapa dura",
            enunciado="Muestra el titulo y el formato de los libros que NO son 'hardcover'. Muestra solo 10 resultados.",
            dificultad="basico",
            sql="SELECT titulo, formato FROM lista_larga WHERE formato != 'hardcover' LIMIT 10",
        ),
        Ejercicio(
            id="c0_06",
            numero=6,
            titulo="Los mejores libros",
            enunciado="Encuentra los 10 libros mejor valorados. Muestra el titulo y la puntuacion, ordenados de mayor a menor puntuacion.",
            dificultad="basico",
            sql="SELECT titulo, puntuacion FROM lista_larga ORDER BY puntuacion DESC LIMIT 10",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_07",
            numero=7,
            titulo="Los peores libros",
            enunciado="Encuentra los 10 libros con peor puntuacion. Muestra el titulo y la puntuacion, ordenados de menor a mayor.",
            dificultad="basico",
            sql="SELECT titulo, puntuacion FROM lista_larga ORDER BY puntuacion LIMIT 10",
            orden_importa=True,
        ),
        # ── INTERMEDIOS (LIKE, BETWEEN, NULL, combinados) ──
        Ejercicio(
            id="c0_08",
            numero=8,
            titulo="Libros con 'The' en el titulo",
            enunciado="Encuentra todos los libros cuyo titulo comienza con la palabra 'The'. Usa LIKE para esta busqueda.",
            dificultad="intermedio",
            sql="SELECT titulo FROM lista_larga WHERE titulo LIKE 'The %'",
        ),
        Ejercicio(
            id="c0_09",
            numero=9,
            titulo="Busqueda por palabra clave",
            enunciado="Encuentra todos los libros que contengan la palabra 'Love' en su titulo, sin importar mayusculas o minusculas.",
            dificultad="intermedio",
            sql="SELECT titulo FROM lista_larga WHERE titulo ILIKE '%Love%'",
        ),
        Ejercicio(
            id="c0_10",
            numero=10,
            titulo="Rango de anios",
            enunciado="Muestra el titulo, autor y anio de los libros publicados entre 2020 y 2022 (inclusive). Ordena por anio.",
            dificultad="intermedio",
            sql="SELECT titulo, autor, anio FROM lista_larga WHERE anio BETWEEN 2020 AND 2022 ORDER BY anio",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_11",
            numero=11,
            titulo="Libros sin traductor",
            enunciado="Encuentra los libros que NO tienen traductor registrado. Muestra solo el titulo.",
            dificultad="intermedio",
            sql="SELECT titulo FROM lista_larga WHERE traductor IS NULL",
        ),
        Ejercicio(
            id="c0_12",
            numero=12,
            titulo="Tapa dura en 2022 o 2023",
            enunciado="Muestra el titulo, formato y anio de los libros que sean 'hardcover' Y publicados en 2022 O 2023. Combina AND y OR con parentesis.",
            dificultad="intermedio",
            sql="SELECT titulo, formato, anio FROM lista_larga WHERE formato = 'hardcover' AND (anio = 2022 OR anio = 2023)",
        ),
        Ejercicio(
            id="c0_13",
            numero=13,
            titulo="Libros cortos bien valorados",
            enunciado="Encuentra libros con menos de 200 paginas y puntuacion mayor a 4.0. Muestra titulo, paginas y puntuacion.",
            dificultad="intermedio",
            sql="SELECT titulo, paginas, puntuacion FROM lista_larga WHERE paginas < 200 AND puntuacion > 4.0",
        ),
        Ejercicio(
            id="c0_14",
            numero=14,
            titulo="Libros con formato especifico",
            enunciado="Muestra los libros que NO son 'paperback' NI 'hardcover'. Muestra el titulo y el formato.",
            dificultad="intermedio",
            sql="SELECT titulo, formato FROM lista_larga WHERE formato NOT IN ('paperback', 'hardcover')",
        ),
        Ejercicio(
            id="c0_15",
            numero=15,
            titulo="Titulos de 4 letras",
            enunciado="Encuentra libros cuyo titulo tenga exactamente 4 caracteres usando el comodin _ de LIKE. Busca en toda la tabla.",
            dificultad="intermedio",
            sql="SELECT titulo FROM lista_larga WHERE titulo LIKE '____'",
        ),
        # ── AVANZADOS (Agregacion, subconsultas, combinado) ──
        Ejercicio(
            id="c0_16",
            numero=16,
            titulo="Puntuacion promedio",
            enunciado="Calcula la puntuacion promedio de todos los libros en lista_larga. Redondea a 2 decimales.",
            dificultad="avanzado",
            sql="SELECT ROUND(AVG(puntuacion)::numeric, 2) AS puntuacion_promedio FROM lista_larga",
        ),
        Ejercicio(
            id="c0_17",
            numero=17,
            titulo="Editoriales distintas",
            enunciado="¿Cuantas editoriales diferentes hay en la tabla lista_larga? Usa COUNT y DISTINCT.",
            dificultad="avanzado",
            sql="SELECT COUNT(DISTINCT editorial) AS total_editoriales FROM lista_larga",
        ),
        Ejercicio(
            id="c0_18",
            numero=18,
            titulo="Estadisticas de puntuacion",
            enunciado="Muestra en una sola consulta: la puntuacion maxima, la minima y la suma total de votos de todos los libros.",
            dificultad="avanzado",
            sql="SELECT MAX(puntuacion) AS maxima, MIN(puntuacion) AS minima, SUM(votos) AS total_votos FROM lista_larga",
        ),
        Ejercicio(
            id="c0_19",
            numero=19,
            titulo="Libros mejor valorados que el promedio",
            enunciado="Muestra el titulo y la puntuacion de los libros cuya puntuacion sea mayor que la puntuacion promedio de todos los libros. Ordena de mayor a menor puntuacion. (Pista: usa una subconsulta).",
            dificultad="avanzado",
            sql="SELECT titulo, puntuacion FROM lista_larga WHERE puntuacion > (SELECT AVG(puntuacion) FROM lista_larga) ORDER BY puntuacion DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_20",
            numero=20,
            titulo="Top 5 con mas votos",
            enunciado="Muestra los 5 libros con mas votos. Incluye titulo, puntuacion y votos. Ordena por votos descendente.",
            dificultad="avanzado",
            sql="SELECT titulo, puntuacion, votos FROM lista_larga ORDER BY votos DESC LIMIT 5",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_21",
            numero=21,
            titulo="Editoriales con mejor promedio",
            enunciado="Para las editoriales que tienen al menos 2 libros, calcula la puntuacion promedio. Muestra la editorial y su promedio redondeado a 2 decimales. Ordena de mayor a menor promedio. (Pista: GROUP BY con HAVING).",
            dificultad="avanzado",
            sql="SELECT editorial, ROUND(AVG(puntuacion)::numeric, 2) AS promedio FROM lista_larga GROUP BY editorial HAVING COUNT(*) >= 2 ORDER BY promedio DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_22",
            numero=22,
            titulo="Conteo por formato",
            enunciado="¿Cuantos libros hay de cada formato? Agrupa por formato, cuenta los libros y ordena por cantidad descendente.",
            dificultad="avanzado",
            sql="SELECT formato, COUNT(*) AS cantidad FROM lista_larga GROUP BY formato ORDER BY cantidad DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_23",
            numero=23,
            titulo="Libros populares con buenas criticas",
            enunciado="Encuentra libros con mas de 10000 votos y puntuacion superior a 4.0. Muestra titulo, puntuacion y votos, ordenados por puntuacion descendente.",
            dificultad="avanzado",
            sql="SELECT titulo, puntuacion, votos FROM lista_larga WHERE votos > 10000 AND puntuacion > 4.0 ORDER BY puntuacion DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_24",
            numero=24,
            titulo="Editorial con mayor puntuacion maxima",
            enunciado="¿Cual es la editorial cuyo libro tiene la mayor puntuacion individual? Muestra la editorial y la puntuacion maxima. (Pista: ORDER BY + LIMIT).",
            dificultad="avanzado",
            sql="SELECT editorial, puntuacion FROM lista_larga ORDER BY puntuacion DESC LIMIT 1",
        ),
        Ejercicio(
            id="c0_25",
            numero=25,
            titulo="Anio con mejor promedio",
            enunciado="Calcula la puntuacion promedio por anio. Muestra anio y promedio redondeado a 2 decimales, ordenado del mejor promedio al peor. (Pista: GROUP BY anio).",
            dificultad="avanzado",
            sql="SELECT anio, ROUND(AVG(puntuacion)::numeric, 2) AS promedio FROM lista_larga GROUP BY anio ORDER BY promedio DESC",
            orden_importa=True,
        ),
        # ── NUEVOS ejercicios aula ──
        Ejercicio(
            id="c0_26",
            numero=26,
            titulo="Usando NOT en vez de !=",
            enunciado="Muestra el titulo y formato de los libros que NO son 'hardcover', pero usando la palabra clave NOT en lugar de !=.",
            dificultad="basico",
            sql="SELECT titulo, formato FROM lista_larga WHERE NOT formato = 'hardcover'",
        ),
        Ejercicio(
            id="c0_27",
            numero=27,
            titulo="Operador <>",
            enunciado="Muestra el titulo y formato de los libros que NO son 'paperback', usando el operador <>.",
            dificultad="basico",
            sql="SELECT titulo, formato FROM lista_larga WHERE formato <> 'paperback'",
        ),
        Ejercicio(
            id="c0_28",
            numero=28,
            titulo="Titulos que terminan con vocal",
            enunciado="Encuentra los libros cuyo titulo termina con la letra 'a'. Usa el comodin % al inicio del patron LIKE.",
            dificultad="basico",
            sql="SELECT titulo FROM lista_larga WHERE titulo LIKE '%a'",
        ),
        Ejercicio(
            id="c0_29",
            numero=29,
            titulo="Dos anios especificos con OR",
            enunciado="Muestra el titulo y anio de los libros publicados en 2018 o en 2023. Usa OR sin parentesis.",
            dificultad="basico",
            sql="SELECT titulo, anio FROM lista_larga WHERE anio = 2018 OR anio = 2023 ORDER BY anio",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_30",
            numero=30,
            titulo="Tres condiciones con AND",
            enunciado="Encuentra libros con mas de 200 paginas, menos de 500 paginas, y puntuacion mayor a 3.5. Muestra titulo, paginas y puntuacion.",
            dificultad="intermedio",
            sql="SELECT titulo, paginas, puntuacion FROM lista_larga WHERE paginas > 200 AND paginas < 500 AND puntuacion > 3.5 ORDER BY puntuacion DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_31",
            numero=31,
            titulo="Fuera de rango con NOT BETWEEN",
            enunciado="Muestra el titulo y anio de los libros publicados FUERA del periodo 2020-2022. Usa NOT BETWEEN.",
            dificultad="intermedio",
            sql="SELECT titulo, anio FROM lista_larga WHERE anio NOT BETWEEN 2020 AND 2022 ORDER BY anio",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_32",
            numero=32,
            titulo="Orden mixto ASC y DESC",
            enunciado="Muestra titulo, anio y puntuacion de todos los libros. Ordena por anio descendente, y dentro del mismo anio por puntuacion ascendente.",
            dificultad="intermedio",
            sql="SELECT titulo, anio, puntuacion FROM lista_larga ORDER BY anio DESC, puntuacion ASC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_33",
            numero=33,
            titulo="MAX y MIN en texto",
            enunciado="¿Cual es el primer y ultimo titulo alfabeticamente en la base de datos? Usa MIN y MAX sobre la columna titulo.",
            dificultad="avanzado",
            sql="SELECT MIN(titulo) AS primer_titulo, MAX(titulo) AS ultimo_titulo FROM lista_larga",
        ),
        Ejercicio(
            id="c0_34",
            numero=34,
            titulo="Suma de votos por formato",
            enunciado="Calcula la suma total de votos para los libros en formato 'paperback' y por separado para los 'hardcover'. Muestra el formato y su suma de votos. Usa GROUP BY.",
            dificultad="avanzado",
            sql="SELECT formato, SUM(votos) AS total_votos FROM lista_larga WHERE formato IN ('paperback', 'hardcover') GROUP BY formato ORDER BY total_votos DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c0_35",
            numero=35,
            titulo="Libros excelentes con pocas paginas",
            enunciado="¿Cuantos libros hay con puntuacion mayor a 4.0 y menos de 250 paginas? Muestra el conteo con un alias descriptivo.",
            dificultad="avanzado",
            sql="SELECT COUNT(*) AS libros_excelentes_cortos FROM lista_larga WHERE puntuacion > 4.0 AND paginas < 250",
        ),
    ]
