from services.ejercicios import Ejercicio


def ejercicios_clase1() -> list[Ejercicio]:
    return [
        # ── BASICOS (JOIN simple, subconsulta simple) ──
        Ejercicio(
            id="c1_01",
            numero=1,
            titulo="Libros con su editorial",
            enunciado="Muestra el titulo de cada libro junto con el nombre de su editorial. Usa JOIN entre libros y editoriales.",
            dificultad="basico",
            sql="SELECT l.titulo, e.editorial FROM libros l JOIN editoriales e ON l.editorial_id = e.id",
        ),
        Ejercicio(
            id="c1_02",
            numero=2,
            titulo="Leones marinos y sus migraciones",
            enunciado="Combina las tablas leones_marinos y migraciones para mostrar el nombre, la especie, la distancia y los dias de migracion de cada leon marino. Usa JOIN ... ON.",
            dificultad="basico",
            sql="SELECT lm.nombre, lm.especie, m.distancia, m.dias FROM leones_marinos lm JOIN migraciones m ON lm.id = m.id",
        ),
        Ejercicio(
            id="c1_03",
            numero=3,
            titulo="Autores con sus libros",
            enunciado="Muestra cada autor junto con los titulos de los libros que ha escrito. Necesitas unir tres tablas: autores, autoria y libros.",
            dificultad="basico",
            sql="SELECT a.nombre, l.titulo FROM autores a JOIN autoria au ON a.id = au.autor_id JOIN libros l ON l.id = au.libro_id ORDER BY a.nombre",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_04",
            numero=4,
            titulo="Libros de Fitzcarraldo Editions",
            enunciado="Usa una subconsulta para encontrar todos los libros publicados por 'Fitzcarraldo Editions'. Muestra solo el titulo.",
            dificultad="basico",
            sql="SELECT titulo FROM libros WHERE editorial_id = (SELECT id FROM editoriales WHERE editorial = 'Fitzcarraldo Editions')",
        ),
        Ejercicio(
            id="c1_05",
            numero=5,
            titulo="Puntuacion promedio de un libro",
            enunciado="Calcula la puntuacion promedio del libro titulado 'Flights'. Usa una subconsulta para encontrar el libro_id. Redondea a 2 decimales.",
            dificultad="basico",
            sql="SELECT ROUND(AVG(puntuacion)::numeric, 2) AS promedio FROM puntuaciones WHERE libro_id = (SELECT id FROM libros WHERE titulo = 'Flights')",
        ),
        Ejercicio(
            id="c1_06",
            numero=6,
            titulo="Todos los leones marinos",
            enunciado="Muestra TODOS los leones marinos, incluso si no tienen datos de migracion. Usa LEFT JOIN.",
            dificultad="basico",
            sql="SELECT lm.nombre, lm.especie, m.distancia, m.dias FROM leones_marinos lm LEFT JOIN migraciones m ON lm.id = m.id",
        ),
        Ejercicio(
            id="c1_07",
            numero=7,
            titulo="Union natural",
            enunciado="Une las tablas leones_marinos y migraciones usando NATURAL JOIN. ¿Que diferencia observas respecto al INNER JOIN?",
            dificultad="basico",
            sql="SELECT * FROM leones_marinos NATURAL JOIN migraciones",
        ),
        # ── INTERMEDIOS (IN, INTERSECT, UNION, EXCEPT, GROUP BY) ──
        Ejercicio(
            id="c1_08",
            numero=8,
            titulo="Libros de Fernanda Melchor",
            enunciado="Encuentra todos los libros escritos por Fernanda Melchor. Usa IN porque un autor puede tener varios libros.",
            dificultad="intermedio",
            sql="SELECT titulo FROM libros WHERE id IN (SELECT libro_id FROM autoria WHERE autor_id = (SELECT id FROM autores WHERE nombre = 'Fernanda Melchor'))",
        ),
        Ejercicio(
            id="c1_09",
            numero=9,
            titulo="Autores que son traductores",
            enunciado="Encuentra las personas que son tanto autoras como traductoras. Usa INTERSECT entre las tablas autores y traductores.",
            dificultad="intermedio",
            sql="SELECT nombre FROM autores INTERSECT SELECT nombre FROM traductores",
        ),
        Ejercicio(
            id="c1_10",
            numero=10,
            titulo="Todos los nombres",
            enunciado="Muestra una lista unica de todas las personas (autores y traductores) sin duplicados. Usa UNION.",
            dificultad="intermedio",
            sql="SELECT nombre FROM autores UNION SELECT nombre FROM traductores",
        ),
        Ejercicio(
            id="c1_11",
            numero=11,
            titulo="Solo traductores",
            enunciado="Encuentra las personas que son traductoras pero NO autoras. Usa EXCEPT.",
            dificultad="intermedio",
            sql="SELECT nombre FROM traductores EXCEPT SELECT nombre FROM autores",
        ),
        Ejercicio(
            id="c1_12",
            numero=12,
            titulo="Puntuacion promedio por libro",
            enunciado="Calcula la puntuacion promedio de cada libro. Muestra el libro_id y el promedio redondeado a 2 decimales. Ordena de mayor a menor promedio. Usa GROUP BY.",
            dificultad="intermedio",
            sql="SELECT libro_id, ROUND(AVG(puntuacion)::numeric, 2) AS promedio FROM puntuaciones GROUP BY libro_id ORDER BY promedio DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_13",
            numero=13,
            titulo="Cantidad de puntuaciones por libro",
            enunciado="¿Cuantas puntuaciones ha recibido cada libro? Muestra el libro_id y el conteo. Ordena por cantidad descendente.",
            dificultad="intermedio",
            sql="SELECT libro_id, COUNT(*) AS total FROM puntuaciones GROUP BY libro_id ORDER BY total DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_14",
            numero=14,
            titulo="Libros con muchos votos",
            enunciado="Muestra los libros que tienen mas de 1000 puntuaciones. Incluye libro_id y el total. Usa GROUP BY con HAVING.",
            dificultad="intermedio",
            sql="SELECT libro_id, COUNT(*) AS total FROM puntuaciones GROUP BY libro_id HAVING COUNT(*) > 1000 ORDER BY total DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_15",
            numero=15,
            titulo="Colaboracion entre traductores",
            enunciado="Encuentra los libros que han sido traducidos TANTO por Sophie Hughes COMO por Margaret Jull Costa. Usa INTERSECT con dos subconsultas sobre la tabla traduccion.",
            dificultad="intermedio",
            sql="SELECT libro_id FROM traduccion WHERE traductor_id = (SELECT id FROM traductores WHERE nombre = 'Sophie Hughes') INTERSECT SELECT libro_id FROM traduccion WHERE traductor_id = (SELECT id FROM traductores WHERE nombre = 'Margaret Jull Costa')",
        ),
        # ── AVANZADOS (Multiples JOIN, subconsultas complejas) ──
        Ejercicio(
            id="c1_16",
            numero=16,
            titulo="Autor de Flights",
            enunciado="Encuentra el nombre del autor que escribio el libro 'Flights'. Necesitas una subconsulta de 3 niveles: libros → autoria → autores.",
            dificultad="avanzado",
            sql="SELECT nombre FROM autores WHERE id = (SELECT autor_id FROM autoria WHERE libro_id = (SELECT id FROM libros WHERE titulo = 'Flights'))",
        ),
        Ejercicio(
            id="c1_17",
            numero=17,
            titulo="Editorial con mas libros",
            enunciado="¿Que editorial tiene mas libros en la base de datos? Muestra el nombre de la editorial y el conteo. Ordena descendente y limita a 1. Usa JOIN + GROUP BY.",
            dificultad="avanzado",
            sql="SELECT e.editorial, COUNT(l.id) AS total FROM editoriales e JOIN libros l ON e.id = l.editorial_id GROUP BY e.editorial ORDER BY total DESC LIMIT 1",
        ),
        Ejercicio(
            id="c1_18",
            numero=18,
            titulo="Libros con mejor promedio (minimo 100 votos)",
            enunciado="Muestra el titulo y la puntuacion promedio de los libros que tienen al menos 100 puntuaciones. Une puntuaciones con libros, agrupa, filtra con HAVING y ordena por promedio descendente. Redondea a 2 decimales.",
            dificultad="avanzado",
            sql="SELECT l.titulo, ROUND(AVG(p.puntuacion)::numeric, 2) AS promedio FROM libros l JOIN puntuaciones p ON l.id = p.libro_id GROUP BY l.id, l.titulo HAVING COUNT(*) >= 100 ORDER BY promedio DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_19",
            numero=19,
            titulo="Profesion de cada persona",
            enunciado="Crea una consulta que muestre cada persona con su profesion ('autor' o 'traductor'). Personas que son ambas deben aparecer en ambas listas. Usa UNION con SELECT de constante.",
            dificultad="avanzado",
            sql="SELECT 'autor' AS profesion, nombre FROM autores UNION SELECT 'traductor' AS profesion, nombre FROM traductores ORDER BY nombre",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_20",
            numero=20,
            titulo="Libros, autores y puntuacion en una consulta",
            enunciado="Para cada libro, muestra su titulo, el nombre de su autor, y su puntuacion promedio redondeada a 2 decimales. Ordena por puntuacion descendente. Necesitas unir 4 tablas: libros, autoria, autores y puntuaciones.",
            dificultad="avanzado",
            sql="SELECT l.titulo, a.nombre AS autor, ROUND(AVG(p.puntuacion)::numeric, 2) AS promedio FROM libros l JOIN autoria au ON l.id = au.libro_id JOIN autores a ON a.id = au.autor_id LEFT JOIN puntuaciones p ON l.id = p.libro_id GROUP BY l.id, l.titulo, a.nombre ORDER BY promedio DESC NULLS LAST",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_21",
            numero=21,
            titulo="El leon marino mas viajero",
            enunciado="Encuentra el leon marino que ha recorrido la mayor distancia total en sus migraciones. Muestra el nombre y la suma de distancias. Usa JOIN + GROUP BY + ORDER BY + LIMIT.",
            dificultad="avanzado",
            sql="SELECT lm.nombre, SUM(m.distancia) AS distancia_total FROM leones_marinos lm JOIN migraciones m ON lm.id = m.id GROUP BY lm.id, lm.nombre ORDER BY distancia_total DESC LIMIT 1",
        ),
        Ejercicio(
            id="c1_22",
            numero=22,
            titulo="Libros de editoriales con puntuacion alta",
            enunciado="Encuentra los libros cuyas editoriales tienen una puntuacion promedio mayor a 3.8. Muestra el titulo del libro y la editorial. (Pista: filtra editoriales con subconsulta en HAVING).",
            dificultad="avanzado",
            sql="SELECT l.titulo, e.editorial FROM libros l JOIN editoriales e ON l.editorial_id = e.id WHERE e.id IN (SELECT e2.id FROM editoriales e2 JOIN libros l2 ON e2.id = l2.editorial_id JOIN puntuaciones p ON l2.id = p.libro_id GROUP BY e2.id HAVING AVG(p.puntuacion) > 3.8) ORDER BY e.editorial, l.titulo",
            orden_importa=True,
        ),
        # ── NUEVOS ejercicios aula ──
        Ejercicio(
            id="c1_23",
            numero=23,
            titulo="RIGHT JOIN: todas las migraciones",
            enunciado="Une las tablas leones_marinos y migraciones usando RIGHT JOIN para asegurar que aparezcan TODAS las migraciones, incluso si el leon marino ya no esta en la tabla leones_marinos.",
            dificultad="basico",
            sql="SELECT lm.nombre, lm.especie, m.distancia, m.dias FROM leones_marinos lm RIGHT JOIN migraciones m ON lm.id = m.id",
        ),
        Ejercicio(
            id="c1_24",
            numero=24,
            titulo="Libros con sus traductores",
            enunciado="Muestra cada libro con el nombre de su traductor. Une las tablas libros, traduccion y traductores. Ordena por titulo.",
            dificultad="basico",
            sql="SELECT l.titulo, t.nombre AS traductor FROM libros l JOIN traduccion tr ON l.id = tr.libro_id JOIN traductores t ON t.id = tr.traductor_id ORDER BY l.titulo",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_25",
            numero=25,
            titulo="FULL JOIN: verlo todo",
            enunciado="Usa FULL JOIN entre leones_marinos y migraciones para ver todos los registros de ambas tablas. Los valores sin correspondencia apareceran como NULL.",
            dificultad="intermedio",
            sql="SELECT lm.nombre, lm.especie, m.distancia, m.dias FROM leones_marinos lm FULL JOIN migraciones m ON lm.id = m.id",
        ),
        Ejercicio(
            id="c1_26",
            numero=26,
            titulo="Libros sin puntuaciones",
            enunciado="Encuentra los libros que NO tienen ninguna puntuacion registrada. Usa LEFT JOIN con puntuaciones y filtra por IS NULL.",
            dificultad="intermedio",
            sql="SELECT l.titulo FROM libros l LEFT JOIN puntuaciones p ON l.id = p.libro_id WHERE p.libro_id IS NULL ORDER BY l.titulo",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_27",
            numero=27,
            titulo="Cuantos libros escribio cada autor",
            enunciado="Muestra cada autor junto con el numero de libros que ha escrito. Usa GROUP BY sobre la tabla autoria. Ordena del mas prolifico al menos.",
            dificultad="intermedio",
            sql="SELECT a.nombre, COUNT(au.libro_id) AS libros_escritos FROM autores a JOIN autoria au ON a.id = au.autor_id GROUP BY a.id, a.nombre ORDER BY libros_escritos DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_28",
            numero=28,
            titulo="Promedio de puntuacion por editorial",
            enunciado="Calcula la puntuacion promedio de los libros agrupados por editorial. Muestra el nombre de la editorial y el promedio redondeado a 2 decimales. Ordena de mayor a menor promedio. Necesitas unir editoriales, libros y puntuaciones.",
            dificultad="intermedio",
            sql="SELECT e.editorial, ROUND(AVG(p.puntuacion)::numeric, 2) AS promedio FROM editoriales e JOIN libros l ON e.id = l.editorial_id JOIN puntuaciones p ON l.id = p.libro_id GROUP BY e.id, e.editorial ORDER BY promedio DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_29",
            numero=29,
            titulo="Autores sin libros registrados",
            enunciado="¿Hay autores en la base de datos que no tienen ningun libro asociado? Usa NOT IN con una subconsulta que obtenga los autor_id de la tabla autoria.",
            dificultad="avanzado",
            sql="SELECT nombre FROM autores WHERE id NOT IN (SELECT DISTINCT autor_id FROM autoria) ORDER BY nombre",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_30",
            numero=30,
            titulo="Autores con mas de un libro",
            enunciado="Muestra los autores que han escrito mas de un libro. Incluye el nombre y la cantidad. Filtra con HAVING COUNT > 1.",
            dificultad="avanzado",
            sql="SELECT a.nombre, COUNT(au.libro_id) AS libros_escritos FROM autores a JOIN autoria au ON a.id = au.autor_id GROUP BY a.id, a.nombre HAVING COUNT(au.libro_id) > 1 ORDER BY libros_escritos DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_31",
            numero=31,
            titulo="Distancia total por leon marino",
            enunciado="Para cada leon marino, calcula la distancia total recorrida sumando todas sus migraciones. Muestra el nombre, la especie y la distancia total. Ordena del mas viajero al menos.",
            dificultad="avanzado",
            sql="SELECT lm.nombre, lm.especie, SUM(m.distancia) AS distancia_total, SUM(m.dias) AS dias_totales FROM leones_marinos lm JOIN migraciones m ON lm.id = m.id GROUP BY lm.id, lm.nombre, lm.especie ORDER BY distancia_total DESC",
            orden_importa=True,
        ),
        Ejercicio(
            id="c1_32",
            numero=32,
            titulo="Libro con autor y traductor",
            enunciado="Muestra el titulo de cada libro junto con el nombre de su autor y su traductor. Necesitas unir 5 tablas: libros, autoria, autores, traduccion y traductores. Limita a 15 resultados.",
            dificultad="avanzado",
            sql="SELECT l.titulo, a.nombre AS autor, t.nombre AS traductor FROM libros l JOIN autoria au ON l.id = au.libro_id JOIN autores a ON a.id = au.autor_id JOIN traduccion tr ON l.id = tr.libro_id JOIN traductores t ON t.id = tr.traductor_id ORDER BY l.titulo LIMIT 15",
            orden_importa=True,
        ),
    ]
